### ISSUE TITLE
sftp documentation refers to a private repository

### ISSUE THREAD

**Issue by pmauduit** [camptocamp/charts-gs#10]
here: https://github.com/camptocamp/charts-gs/blob/main/sftp/README.md?plain=1#L3

Maybe we could at least provide a simple dockerfile to be able to build a simple sftp image. Without all the rancher shenanigans that we did in the past.

**Comment by pmauduit** [comment]
at least the docker images are public

**Comment by edevosc2c** [comment]
moved to https://github.com/camptocamp/georchestra-docker-images/tree/master/sftp-server
