### ISSUE TITLE
sftp: have a custom hostname displayed

### ISSUE THREAD

**Issue by edevosc2c** [camptocamp/charts-gs#17]
It would be ideal for the user to have an easy and recognizable hostname displayed in the shell prompt.

Instead of `sftp-admin-sftp-depl-5c7844964c-jmrtx`, have `dge-sftp-admin`

@jeanmi151 requested this feature

**Comment by jeanmi151** [comment]
found solution: 
`hostname: sftp-admin-tructruc`
in the container deployement

**Comment by edevosc2c** [comment]
added in https://github.com/camptocamp/charts-gs/pull/18
